version: '3'

services:
  app:
    image: docker.io/beejay/webfinger:latest
    ports:
      - "3000:80"  # HTTP-Port
      - "3000:443"  # HTTP-Port

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
