version: '3'
services:
  app:
    image: docker.io/beejay/webfinger:1.28
    ports:
      - 80:3000
      - 443:3000
    environment:
      - ROOT_PATH=/
      - ROOT_DOMAIN=bajonczak.com
      - GHOST_API_KEY=
      - GHOST_BLOG_DOMAIN=blog.bajonczak.com
      - PROFILE_HOMEPAGE=https://blog.bajonczak.com
      - IMAGE_AVATAR_URL=https://blog.bajonczak.com/content/images/2022/10/20221014_171637.png
      - ICON_AVATAR_URL=https://blog.bajonczak.com/content/images/2022/10/20221014_171637.png
      - PUB_KEY=-----BEGIN PUBLIC KEY-----ABC-----END PUBLIC KEY-----